# netlify.toml
[build]
  functions = "netlify/functions" # Indica a Netlify dónde encontrar tus funciones

[[redirects]]
  from = "/api/pokemontcg/*" # La ruta que tu frontend usará para el proxy
  to = "/.netlify/functions/pokemon-proxy/:splat" # Redirige a tu función sin servidor
  status = 200 # Asegura que la redirección sea transparente

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[functions] # <--- NUEVA SECCIÓN
  node_bundler = "esbuild" # <--- Configuración para el empaquetado de Node.js
  external_node_modules = ["node-fetch"] # <--- Asegura que node-fetch se incluya
  timeout = 60 # <--- Aumenta el tiempo de espera de la función a 60 segundos (valor en segundos)
