[build]
  functions = "netlify/functions"
  publish = "."

# Redirect para la API de Pokémon
[[redirects]]
  from = "/api/pokemontcg/*"
  to = "/.netlify/functions/pokemon-proxy"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"